### ISSUE TITLE
Four time interval related fields under case.diagnoses should be 'long' or 'integer' type instead of 'double'

### ISSUE THREAD

**Issue by junjun-zhang** [NCI-GDC/gdc-models#15]
Here is the fragment of the mapping shows the four fields:
https://github.com/NCI-GDC/gdc-models/blob/288157398d5bf239203be03a6442443e46d76067/es-models/case_centric/case_centric.mapping.yaml#L49-L60
```
      age_at_diagnosis:
        type: double
      days_to_birth:
        type: double
      days_to_death:
        type: double
      days_to_last_follow_up:
        type: double
```
This affects all four centric indexes. `gdc_from_graph` is fine.
